### ISSUE TITLE
Pokebot

### ISSUE THREAD

**Issue by ItsTepkey** [40Cakes/pokebot-bizhawk#47]
hello. im all new to this so probably an easy fix but when i start the bot i dont get a dashboard. the window pops up but its completely white

**Comment by PeteKempDojo** [comment]
We've had a couple of reports of this in the discord, a couple of users fixed it by deleting the bot files and re-downloading them and reconfiguring it again. Can you try that

**Comment by pekempy** [comment]
> how would i configure them? sorry completely new to all this  

Follow the wiki which has all the steps laid out :)
https://github.com/40Cakes/pokebot-bizhawk/wiki/Getting-started

**Comment by AlexTheM8** [comment]
I also had this issue, but it was due to a permissions conflict. If you're still having trouble, find `webview.start()` in `bot.py` and update it like so:

`webview.start(storage_path="C:/Arbitrary/Path/To/Store/WebData")`

It can be almost any path as long as it has general permissions to access. Example: `C:\Users\YourName\Desktop\web-storage`
